Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'

Style/RaiseArgs:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

Rails/SkipsModelValidations:
  Enabled: false

# Check with yard instead.
Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
