version: "3"

volumes:
  certs:
    external: false

services:
  memcached:
    image: memcached:alpine
  webserver:
    build:
      context: ./nginx
      dockerfile: docker/Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
    depends_on:
      - api
  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
  api:
    image: driggl/wdf_api:latest
    env_file:
      - .env_api_prod
    command: sh bin/start
    ports:
      - "3000:3000"
