
default: &default
  adapter: <%= ENV['DB_ADAPTER'] %>
  encoding: unicode
  pool: 5
  user: <%= ENV['DB_USER'] %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: 5432

development:
  <<: *default
  database: wdf_development

test:
  <<: *default
  database: wdf_test

production:
  <<: *default
  prepared_statements: false
  port: <%= ENV['DB_PORT'] %>
