
default: &default
  adapter: postgresql
  encoding: unicode
  user: <%= ENV['DB_USER'] %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wdf_development

test:
  <<: *default
  database: wdf_test

production:
  port: <%= ENV['DB_PORT'] %>
  <<: *default
  password: <%= ENV['DB_PASSWORD'] %>
